routes:
  portfolios:
    portfolio_details:
  contacts:

resources:
  portfolios:
    user: references
    name:
      type: string
      null: false
      limit: 50
    url:
      type: string
      limit: 300
  portfolio_details:
    portfolio: references
    status:
      type: integer
      null: false
  contacts:
    user: references
    subjet:
      type: string
      null: false
      limit: 80
    detail:
      type: string
      null: false
      limit: 600
