# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 676e2dcd432c27e21863d3ebd3a5a19d8e2091be07efefe2cbd740594ac1e2ab18af1ed4da07150e638cd078755309b4cb26197b14919a6327832bdbf853add4

test:
  secret_key_base: 398d9a75e66b69d2c7771b7d069078226a792f6c91a6150ba812553a820636528c2afc68f617960329da54ef36bc465b5900b2f59cf906d43617b2c31e878eca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
